package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"
)

// EvidenceReport is a structured compliance evidence document for regulatory submissions.
type EvidenceReport struct {
	ReportID     string              `json:"report_id"`
	GeneratedAt  time.Time           `json:"generated_at"`
	TenantID     string              `json:"tenant_id"`
	Framework    string              `json:"framework"`
	ReportPeriod EvidencePeriod      `json:"report_period"`
	Summary      EvidenceSummary     `json:"summary"`
	PostureScore PostureSnapshot     `json:"posture_score"`
	Assessment   *AssessmentResult   `json:"assessment,omitempty"`
	Controls     []FrameworkControl  `json:"controls"`
	Gaps         []ComplianceGap     `json:"gaps"`
	KeyHygiene   *KeyHygieneReport   `json:"key_hygiene,omitempty"`
	Attestation  EvidenceAttestation `json:"attestation"`
	ExportFormat string              `json:"export_format"`
}

type EvidencePeriod struct {
	From time.Time `json:"from"`
	To   time.Time `json:"to"`
}

type EvidenceSummary struct {
	OverallScore     int    `json:"overall_score"`
	ControlsPassing  int    `json:"controls_passing"`
	ControlsFailing  int    `json:"controls_failing"`
	GapsOpen         int    `json:"gaps_open"`
	GapsCritical     int    `json:"gaps_critical"`
	ComplianceStatus string `json:"compliance_status"`
	NarrativeSummary string `json:"narrative_summary"`
}

type EvidenceAttestation struct {
	GeneratedBy string    `json:"generated_by"`
	System      string    `json:"system"`
	Version     string    `json:"version"`
	Timestamp   time.Time `json:"timestamp"`
	Note        string    `json:"note"`
}

// handleEvidenceExport generates a downloadable compliance evidence document.
// GET /compliance/evidence/export?framework=gdpr&format=json&period=30d
func (h *Handler) handleEvidenceExport(w http.ResponseWriter, r *http.Request) {
	reqID := requestID(r)
	tenantID := mustTenant(r, reqID, w)
	if tenantID == "" {
		return
	}

	framework := strings.ToLower(strings.TrimSpace(r.URL.Query().Get("framework")))
	if framework == "" {
		framework = "gdpr"
	}
	format := strings.ToLower(strings.TrimSpace(r.URL.Query().Get("format")))
	if format == "" {
		format = "json"
	}
	periodStr := strings.TrimSpace(r.URL.Query().Get("period"))
	if periodStr == "" {
		periodStr = "30d"
	}

	// Resolve period.
	periodDays := 30
	switch periodStr {
	case "7d":
		periodDays = 7
	case "90d":
		periodDays = 90
	case "1y":
		periodDays = 365
	}
	periodTo := time.Now().UTC()
	periodFrom := periodTo.AddDate(0, 0, -periodDays)

	// Gather posture snapshot.
	posture, err := h.svc.GetPosture(r.Context(), tenantID, false)
	if err != nil {
		h.writeServiceError(w, err, reqID, tenantID)
		return
	}

	// Gather latest assessment.
	assessment, _ := h.svc.GetLatestAssessment(r.Context(), tenantID, "")
	// If missing, run a fresh assessment.
	if assessment.ID == "" {
		assessment, _ = h.svc.RunAssessment(r.Context(), tenantID, "evidence_export", true, "")
	}

	// Gather framework controls and assessment for the requested framework.
	controls, _, _ := h.svc.GetFrameworkControls(r.Context(), tenantID, framework)

	// Gather gaps.
	gaps, _ := h.svc.GetFrameworkGaps(r.Context(), tenantID, framework)

	// Gather key hygiene.
	hygiene, _ := h.svc.GetKeyHygieneReport(r.Context(), tenantID)

	// Build summary from framework controls.
	passing := 0
	failing := 0
	for _, c := range controls {
		if c.Score >= 70 {
			passing++
		} else {
			failing++
		}
	}
	openGaps := 0
	critGaps := 0
	for _, g := range gaps {
		if g.Status != "resolved" {
			openGaps++
			if strings.EqualFold(g.Severity, "critical") {
				critGaps++
			}
		}
	}

	status := "compliant"
	if posture.OverallScore < 60 || critGaps > 0 {
		status = "non_compliant"
	} else if posture.OverallScore < 80 || openGaps > 0 {
		status = "partial"
	}

	narrative := buildNarrative(framework, posture.OverallScore, passing, failing, openGaps, critGaps)

	report := EvidenceReport{
		ReportID:    newID("evid"),
		GeneratedAt: time.Now().UTC(),
		TenantID:    tenantID,
		Framework:   framework,
		ReportPeriod: EvidencePeriod{
			From: periodFrom,
			To:   periodTo,
		},
		Summary: EvidenceSummary{
			OverallScore:     posture.OverallScore,
			ControlsPassing:  passing,
			ControlsFailing:  failing,
			GapsOpen:         openGaps,
			GapsCritical:     critGaps,
			ComplianceStatus: status,
			NarrativeSummary: narrative,
		},
		PostureScore: posture,
		Controls:     controls,
		Gaps:         gaps,
		Attestation: EvidenceAttestation{
			GeneratedBy: "Vecta KMS Compliance Service",
			System:      "vecta-kms",
			Version:     "1.0",
			Timestamp:   time.Now().UTC(),
			Note:        "This evidence report is machine-generated by the Vecta KMS platform. It reflects the cryptographic posture and control state at the time of generation and must be reviewed by a qualified compliance officer before submission to a regulatory authority.",
		},
		ExportFormat: format,
	}

	if hygiene.TotalKeys > 0 {
		report.KeyHygiene = &hygiene
	}
	if assessment.ID != "" {
		report.Assessment = &assessment
	}

	// Filename suggestion.
	filename := fmt.Sprintf("compliance-evidence-%s-%s-%s.json",
		framework,
		tenantID,
		time.Now().UTC().Format("2006-01-02"),
	)

	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	w.Header().Set("X-Request-ID", reqID)
	w.WriteHeader(http.StatusOK)
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	_ = enc.Encode(report)
}

func buildNarrative(framework string, score, passing, failing, openGaps, critGaps int) string {
	frameworkName := frameworkDisplayName(framework)
	statusText := "demonstrates strong compliance"
	if score < 60 {
		statusText = "shows significant compliance gaps requiring immediate remediation"
	} else if score < 80 {
		statusText = "shows partial compliance with areas requiring improvement"
	}

	return fmt.Sprintf(
		"This evidence report covers the organization's cryptographic key management practices as assessed against %s. "+
			"The system achieved an overall compliance score of %d/100 and %s. "+
			"%d controls are passing and %d require attention. "+
			"There are %d open gap(s), of which %d are critical severity.",
		frameworkName, score, statusText, passing, failing, openGaps, critGaps,
	)
}

func frameworkDisplayName(id string) string {
	switch strings.ToLower(id) {
	case "gdpr":
		return "GDPR Article 32 (Technical and Organisational Measures)"
	case "nis2":
		return "NIS2 Directive (Network and Information Systems Security)"
	case "pci-dss-4.0", "pci-dss":
		return "PCI DSS 4.0 (Payment Card Industry Data Security Standard)"
	case "fips-140-3", "fips":
		return "FIPS 140-3 (Federal Information Processing Standard)"
	case "nist-800-57", "nist":
		return "NIST SP 800-57 (Key Management Recommendations)"
	case "iso27001":
		return "ISO/IEC 27001 (Information Security Management)"
	case "eidas":
		return "eIDAS Regulation (Electronic Identification and Trust Services)"
	default:
		return strings.ToUpper(id)
	}
}
