// suite.go is the single approved entry point for cryptographic primitives
// across all Vecta KMS services. Services MUST NOT import crypto/aes,
// crypto/rsa, crypto/ecdsa, crypto/ed25519 or crypto/rand directly; the
// conformance check (scripts/conformance.sh) enforces this. Every operation
// here is gated by pkg/fips when VECTA_FIPS_MODE is enabled.
package crypto

import (
	"crypto"
	"crypto/aes"
	"crypto/cipher"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/hmac"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/sha512"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"hash"
	"io"
	"strings"

	"vecta-kms/pkg/fips"
)

// Reader is the only sanctioned source of cryptographic randomness.
var Reader io.Reader = rand.Reader

// Canonical algorithm identifiers accepted by GenerateKeyPair, Sign and Verify.
const (
	AlgRSA2048   = "RSA-2048"
	AlgRSA3072   = "RSA-3072"
	AlgRSA4096   = "RSA-4096"
	AlgECDSAP256 = "ECDSA-P256"
	AlgECDSAP384 = "ECDSA-P384"
	AlgEd25519   = "ED25519"
	AlgAES128GCM = "AES-128-GCM"
	AlgAES256GCM = "AES-256-GCM"
)

// RandomBytes returns n cryptographically secure random bytes.
func RandomBytes(n int) ([]byte, error) {
	if n <= 0 {
		return nil, errors.New("crypto: byte count must be positive")
	}
	b := make([]byte, n)
	if _, err := io.ReadFull(Reader, b); err != nil {
		return nil, err
	}
	return b, nil
}

// GenerateAESKey returns a new AES key of the given bit size (128 or 256).
func GenerateAESKey(bits int) ([]byte, error) {
	if bits != 128 && bits != 256 {
		return nil, fmt.Errorf("crypto: unsupported AES key size %d", bits)
	}
	if err := fips.ValidateKeyLength("AES", bits); err != nil {
		return nil, err
	}
	return RandomBytes(bits / 8)
}

// KeyPair holds an asymmetric key pair generated by GenerateKeyPair.
type KeyPair struct {
	Algorithm string
	Private   crypto.Signer
	Public    crypto.PublicKey
}

// GenerateKeyPair creates an asymmetric key pair for a canonical algorithm
// identifier (e.g. "RSA-4096", "ECDSA-P256", "ED25519").
func GenerateKeyPair(algorithm string) (*KeyPair, error) {
	alg := strings.ToUpper(strings.TrimSpace(algorithm))
	if err := fips.EnforceApproved(alg); err != nil {
		return nil, err
	}
	var (
		signer crypto.Signer
		err    error
	)
	switch alg {
	case AlgRSA2048:
		signer, err = rsa.GenerateKey(Reader, 2048)
	case AlgRSA3072:
		signer, err = rsa.GenerateKey(Reader, 3072)
	case AlgRSA4096:
		signer, err = rsa.GenerateKey(Reader, 4096)
	case AlgECDSAP256:
		signer, err = ecdsa.GenerateKey(elliptic.P256(), Reader)
	case AlgECDSAP384:
		signer, err = ecdsa.GenerateKey(elliptic.P384(), Reader)
	case AlgEd25519:
		_, signer, err = ed25519.GenerateKey(Reader)
	default:
		return nil, fmt.Errorf("crypto: unsupported key pair algorithm %q", algorithm)
	}
	if err != nil {
		return nil, err
	}
	return &KeyPair{Algorithm: alg, Private: signer, Public: signer.Public()}, nil
}

// Sign signs data with the key pair's native scheme: RSA-PSS over SHA-256 for
// RSA keys, SHA-256/SHA-384 ECDSA for P-256/P-384, and pure Ed25519.
func Sign(kp *KeyPair, data []byte) ([]byte, error) {
	if kp == nil || kp.Private == nil {
		return nil, errors.New("crypto: nil key pair")
	}
	if err := fips.EnforceApproved(kp.Algorithm); err != nil {
		return nil, err
	}
	switch strings.ToUpper(kp.Algorithm) {
	case AlgRSA2048, AlgRSA3072, AlgRSA4096:
		digest := sha256.Sum256(data)
		return kp.Private.Sign(Reader, digest[:], &rsa.PSSOptions{Hash: crypto.SHA256, SaltLength: rsa.PSSSaltLengthEqualsHash})
	case AlgECDSAP256:
		digest := sha256.Sum256(data)
		return kp.Private.Sign(Reader, digest[:], crypto.SHA256)
	case AlgECDSAP384:
		digest := sha512.Sum384(data)
		return kp.Private.Sign(Reader, digest[:], crypto.SHA384)
	case AlgEd25519:
		return kp.Private.Sign(Reader, data, crypto.Hash(0))
	default:
		return nil, fmt.Errorf("crypto: unsupported signing algorithm %q", kp.Algorithm)
	}
}

// Verify checks a signature produced by Sign.
func Verify(algorithm string, pub crypto.PublicKey, data []byte, sig []byte) error {
	switch strings.ToUpper(strings.TrimSpace(algorithm)) {
	case AlgRSA2048, AlgRSA3072, AlgRSA4096:
		rsaPub, ok := pub.(*rsa.PublicKey)
		if !ok {
			return errors.New("crypto: public key is not RSA")
		}
		digest := sha256.Sum256(data)
		return rsa.VerifyPSS(rsaPub, crypto.SHA256, digest[:], sig, &rsa.PSSOptions{Hash: crypto.SHA256, SaltLength: rsa.PSSSaltLengthEqualsHash})
	case AlgECDSAP256:
		ecPub, ok := pub.(*ecdsa.PublicKey)
		if !ok {
			return errors.New("crypto: public key is not ECDSA")
		}
		digest := sha256.Sum256(data)
		if !ecdsa.VerifyASN1(ecPub, digest[:], sig) {
			return errors.New("crypto: ecdsa signature verification failed")
		}
		return nil
	case AlgECDSAP384:
		ecPub, ok := pub.(*ecdsa.PublicKey)
		if !ok {
			return errors.New("crypto: public key is not ECDSA")
		}
		digest := sha512.Sum384(data)
		if !ecdsa.VerifyASN1(ecPub, digest[:], sig) {
			return errors.New("crypto: ecdsa signature verification failed")
		}
		return nil
	case AlgEd25519:
		edPub, ok := pub.(ed25519.PublicKey)
		if !ok {
			return errors.New("crypto: public key is not Ed25519")
		}
		if !ed25519.Verify(edPub, data, sig) {
			return errors.New("crypto: ed25519 signature verification failed")
		}
		return nil
	default:
		return fmt.Errorf("crypto: unsupported verification algorithm %q", algorithm)
	}
}

// Hash computes a FIPS-approved digest ("SHA-256", "SHA-384", "SHA-512").
func Hash(algorithm string, data []byte) ([]byte, error) {
	h, err := newHash(algorithm)
	if err != nil {
		return nil, err
	}
	h.Write(data)
	return h.Sum(nil), nil
}

// HMAC computes an HMAC with an approved hash ("SHA-256", "SHA-384", "SHA-512").
func HMAC(algorithm string, key []byte, data []byte) ([]byte, error) {
	if err := fips.ValidateKeyLength("HMAC", len(key)*8); err != nil {
		return nil, err
	}
	mac := hmac.New(func() hash.Hash {
		h, _ := newHash(algorithm)
		return h
	}, key)
	if _, err := mac.Write(data); err != nil {
		return nil, err
	}
	return mac.Sum(nil), nil
}

// VerifyHMAC recomputes and compares an HMAC in constant time.
func VerifyHMAC(algorithm string, key []byte, data []byte, expected []byte) bool {
	got, err := HMAC(algorithm, key, data)
	if err != nil {
		return false
	}
	return hmac.Equal(got, expected)
}

func newHash(algorithm string) (hash.Hash, error) {
	alg := strings.ToUpper(strings.TrimSpace(algorithm))
	if err := fips.EnforceApproved(alg); err != nil {
		return nil, err
	}
	switch alg {
	case "SHA-256":
		return sha256.New(), nil
	case "SHA-384":
		return sha512.New384(), nil
	case "SHA-512":
		return sha512.New(), nil
	default:
		return nil, fmt.Errorf("crypto: unsupported hash algorithm %q", algorithm)
	}
}

// Seal encrypts plaintext with AES-GCM (key of 16 or 32 bytes) and returns
// nonce||ciphertext. aad is optional additional authenticated data.
func Seal(key []byte, plaintext []byte, aad []byte) ([]byte, error) {
	gcm, err := newGCM(key)
	if err != nil {
		return nil, err
	}
	nonce, err := RandomBytes(gcm.NonceSize())
	if err != nil {
		return nil, err
	}
	return gcm.Seal(nonce, nonce, plaintext, aad), nil
}

// Open decrypts a blob produced by Seal.
func Open(key []byte, blob []byte, aad []byte) ([]byte, error) {
	gcm, err := newGCM(key)
	if err != nil {
		return nil, err
	}
	if len(blob) < gcm.NonceSize() {
		return nil, errors.New("crypto: ciphertext shorter than nonce")
	}
	return gcm.Open(nil, blob[:gcm.NonceSize()], blob[gcm.NonceSize():], aad)
}

func newGCM(key []byte) (cipher.AEAD, error) {
	if len(key) != 16 && len(key) != 32 {
		return nil, fmt.Errorf("crypto: AES key must be 16 or 32 bytes, got %d", len(key))
	}
	if err := fips.ValidateKeyLength("AES", len(key)*8); err != nil {
		return nil, err
	}
	blk, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	return cipher.NewGCM(blk)
}

// MarshalPrivateKeyPEM encodes a private key as PKCS#8 PEM.
func MarshalPrivateKeyPEM(kp *KeyPair) ([]byte, error) {
	if kp == nil || kp.Private == nil {
		return nil, errors.New("crypto: nil key pair")
	}
	der, err := x509.MarshalPKCS8PrivateKey(kp.Private)
	if err != nil {
		return nil, err
	}
	return pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: der}), nil
}

// MarshalPublicKeyPEM encodes a public key as PKIX PEM.
func MarshalPublicKeyPEM(pub crypto.PublicKey) ([]byte, error) {
	der, err := x509.MarshalPKIXPublicKey(pub)
	if err != nil {
		return nil, err
	}
	return pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der}), nil
}

// ParsePrivateKeyPEM decodes a PKCS#8, PKCS#1 (RSA) or SEC1 (EC) PEM
// private key back into a KeyPair.
func ParsePrivateKeyPEM(pemBytes []byte) (*KeyPair, error) {
	block, _ := pem.Decode(pemBytes)
	if block == nil {
		return nil, errors.New("crypto: no PEM block found")
	}
	keyAny, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		if rsaKey, rsaErr := x509.ParsePKCS1PrivateKey(block.Bytes); rsaErr == nil {
			keyAny = rsaKey
		} else if ecKey, ecErr := x509.ParseECPrivateKey(block.Bytes); ecErr == nil {
			keyAny = ecKey
		} else {
			return nil, err
		}
	}
	signer, ok := keyAny.(crypto.Signer)
	if !ok {
		return nil, errors.New("crypto: parsed key does not implement crypto.Signer")
	}
	alg, err := algorithmOf(signer)
	if err != nil {
		return nil, err
	}
	return &KeyPair{Algorithm: alg, Private: signer, Public: signer.Public()}, nil
}

func algorithmOf(signer crypto.Signer) (string, error) {
	switch k := signer.(type) {
	case *rsa.PrivateKey:
		return fmt.Sprintf("RSA-%d", k.N.BitLen()), nil
	case *ecdsa.PrivateKey:
		switch k.Curve {
		case elliptic.P256():
			return AlgECDSAP256, nil
		case elliptic.P384():
			return AlgECDSAP384, nil
		default:
			return "", fmt.Errorf("crypto: unsupported ECDSA curve %s", k.Curve.Params().Name)
		}
	case ed25519.PrivateKey:
		return AlgEd25519, nil
	default:
		return "", errors.New("crypto: unsupported private key type")
	}
}
