// Code generated from services/*/migrations and hand-classified; keep in step.
// Every table a service creates must appear exactly once below (enforced by
// TestEveryTableIsClassified).

package clustercatalog

// Replicated maps a cluster component to the tables it owns. A member that
// is assigned the component receives these tables from the primary.
var Replicated = map[string][]string{
	"ai": {
		"ai_gateway_access_rules",
		"ai_gateway_guardrails",
		"ai_gateway_policies",
		"ai_gateway_providers",
	},
	"audit": {
		"alert_rules",
		"webhooks",
	},
	"auth": {
		"auth_api_keys",
		"auth_client_registrations",
		"auth_group_role_bindings",
		"auth_identity_provider_configs",
		"auth_password_policies",
		"auth_scim_group_members",
		"auth_scim_groups",
		"auth_scim_settings",
		"auth_scim_user_links",
		"auth_security_policies",
		"auth_tenant_roles",
		"auth_tenants",
		"auth_users",
	},
	"autokey": {
		"autokey_handles",
		"autokey_requests",
		"autokey_service_policies",
		"autokey_settings",
		"autokey_templates",
	},
	"byok": {
		"cloud_accounts",
		"cloud_key_bindings",
		"cloud_mek_exposure",
		"cloud_mek_state",
		"cloud_region_mappings",
		"cloud_sync_jobs",
	},
	"certs": {
		"cert_acme_accounts",
		"cert_acme_orders",
		"cert_acme_star_subscriptions",
		"cert_cas",
		"cert_certificates",
		"cert_clm_policies",
		"cert_deleted_refs",
		"cert_expiry_alert_policies",
		"cert_expiry_alert_state",
		"cert_mek_exposure",
		"cert_mek_state",
		"cert_merkle_epochs",
		"cert_merkle_leaves",
		"cert_profiles",
		"cert_protocol_configs",
		"cert_renewal_intelligence",
		"cert_revocations",
		"ct_alerts",
		"ct_watched_domains",
		"mesh_certificates",
		"mesh_services",
		"mesh_topology",
		"mesh_trust_anchors",
	},
	"compliance": {
		"compliance_assessment_runs",
		"compliance_assessment_schedules",
		"compliance_cbom_snapshots",
		"compliance_framework_assessments",
		"compliance_gaps",
		"compliance_playbook_runs",
		"compliance_playbooks",
		"compliance_posture_snapshots",
		"compliance_templates",
	},
	"confidential": {
		"confidential_attestation_policy",
	},
	"dataprotect": {
		"data_protection_policy",
		"dataprotect_kdf_meta",
		"dataprotect_key_kdf",
		"field_encryption_leases",
		"field_encryption_wrappers",
		"field_protection_profiles",
		"masking_policies",
		"redaction_policies",
		"token_vaults",
		"tokens",
	},
	"discovery": {
		"discovery_assets",
		"discovery_scans",
		"lineage_events",
	},
	"ekm": {
		"ekm_agents",
		"ekm_azure_configs",
		"ekm_azure_key_mappings",
		"ekm_bitlocker_clients",
		"ekm_bitlocker_jobs",
		"ekm_bitlocker_recovery_keys",
		"ekm_databases",
		"ekm_google_cse_configs",
		"ekm_google_cse_keys",
		"ekm_mek_exposure",
		"ekm_mek_state",
		"ekm_tde_keys",
	},
	"featureforge": {
		"ff_approvals",
		"ff_intents",
	},
	"governance": {
		"approval_policies",
		"approval_requests",
		"approval_tokens",
		"approval_votes",
		"governance_settings",
		"platform_fips_mode",
	},
	"hyok": {
		"hyok_endpoints",
	},
	"keyaccess": {
		"key_access_rules",
		"key_access_settings",
	},
	"keycore": {
		"keycore_system_keys",
		"agility_migration_plans",
		"canary_keys",
		"ceremonies",
		"ceremony_guardians",
		"ceremony_shares",
		"compromise_events",
		"dr_drill_schedules",
		"edge_devices",
		"enterprise_control_records",
		"envelope_deks",
		"envelope_keks",
		"envelope_rewrap_jobs",
		"escrow_guardians",
		"escrow_policies",
		"escrow_recovery_requests",
		"escrowed_keys",
		"external_credential_bindings",
		"kdf_configs",
		"key_access_grants",
		"key_access_group_members",
		"key_access_groups",
		"key_access_policy_settings",
		"key_audit_chain_anchors",
		"key_binding_configs",
		"key_dependencies",
		"key_dspm_findings",
		"key_health_scores",
		"key_interface_subject_policies",
		"key_inventory",
		"key_metadata_ext",
		"key_rotation_metrics",
		"key_scheduling_jobs",
		"key_sharing_tokens",
		"key_tags",
		"key_versions",
		"keys",
		"rotation_analytics_snapshot",
		"rotation_policies",
		"rotation_runs",
	},
	"kmip": {
		"kmip_client_profiles",
		"kmip_clients",
		"kmip_interop_targets",
		"kmip_objects",
	},
	"payment": {
		"payment_ap2_profile",
		"payment_injection_jobs",
		"payment_injection_terminals",
		"payment_keys",
		"payment_policy",
		"tr31_translations",
	},
	"policy": {
		"policies",
		"policy_versions",
	},
	"posture": {
		"leak_findings",
		"leak_scan_jobs",
		"leak_scan_targets",
		"posture_actions",
		"posture_events_history",
		"posture_findings",
		"posture_risk_snapshots",
	},
	"pqc": {
		"pqc_migration_plans",
		"pqc_migration_runs",
		"pqc_policies",
		"pqc_readiness_scans",
	},
	"reporting": {
		"reporting_alert_rules",
		"reporting_alerts",
		"reporting_incidents",
		"reporting_notification_channels",
		"reporting_report_jobs",
		"reporting_scheduled_reports",
		"reporting_severity_overrides",
	},
	"sbom": {
		"cbom_snapshots",
		"sbom_manual_advisories",
		"sbom_snapshots",
	},
	"secrets": {
		"secret_values",
		"secrets",
		"secrets_mek_exposure",
		"secrets_mek_state",
	},
	"signing": {
		"signing_profiles",
		"signing_settings",
	},
	"workload": {
		"workload_identity_federation",
		"workload_identity_registrations",
		"workload_identity_settings",
	},
}

// NodeLocal tables are never replicated: they hold data that belongs to one
// node (its sessions, logs written during crypto operations, hardware and
// network settings, backups, cluster control plane).
var NodeLocal = map[string]string{
	"key_op_counters":                     "per-key operation counters of a cluster member (written during crypto operations)",
	"cluster_local_state":                 "this node's cluster role and its primary; the forwarding credential authenticates this node only",
	"cluster_member_credentials":          "credentials a primary issued to its members",
	"ai_gateway_audit":                    "per-node AI gateway log",
	"ai_gateway_token_budgets":            "per-node usage counters",
	"alerts":                              "alerts raised on this node",
	"auth_hsm_provider_configs":           "HSM hardware configuration of this node",
	"auth_request_nonce_cache":            "anti-replay nonces are checked where the request lands",
	"auth_sessions":                       "sessions are bound to the node that issued them",
	"backup_policies":                     "backups are taken and restored per node",
	"backup_restore_points":               "backups are taken and restored per node",
	"backup_runs":                         "backups are taken and restored per node",
	"canary_trip_events":                  "per-node canary trip log",
	"cluster_join_tokens":                 "cluster control plane; exchanged through the join and heartbeat API, not table replication",
	"cluster_nodes":                       "cluster control plane; exchanged through the join and heartbeat API, not table replication",
	"cluster_operation_logs":              "cluster control plane; exchanged through the join and heartbeat API, not table replication",
	"cluster_profiles":                    "cluster control plane; exchanged through the join and heartbeat API, not table replication",
	"cluster_sync_checkpoints":            "cluster control plane; exchanged through the join and heartbeat API, not table replication",
	"cluster_sync_events":                 "cluster control plane; exchanged through the join and heartbeat API, not table replication",
	"cluster_sync_nonces":                 "cluster control plane; exchanged through the join and heartbeat API, not table replication",
	"confidential_release_history":        "per-node release log",
	"ct_log_entries":                      "CT log polling cursor data of this node",
	"fle_metadata":                        "where fields were encrypted; written during crypto operations on the node that served them",
	"dataprotect_audit_log":               "per-node data protection log",
	"dr_drill_runs":                       "DR drill executions of this node",
	"ekm_key_access_log":                  "per-node access log",
	"ff_events":                           "per-node feature-forge event log",
	"field_encryption_usage_receipts":     "usage receipts reported to this node",
	"field_encryption_wrapper_challenges": "short-lived challenges issued by this node",
	"governance_backup_jobs":              "backups taken on this node",
	"governance_system_state":             "node settings: network, FDE, HSM, SNMP, entropy",
	"hyok_requests":                       "per-node request log",
	"kdf_derivation_log":                  "per-node derivation log written during crypto operations",
	"key_access_decisions":                "per-node access decision log",
	"key_analytics_metrics":               "per-node operation metrics",
	"key_interface_ports":                 "network listeners of this node",
	"key_interface_tls_defaults":          "TLS listener defaults of this node",
	"key_iv_log":                          "per-node IV log written during crypto operations",
	"key_request_nonce_cache":             "anti-replay nonces are checked where the request lands",
	"key_usage_events":                    "per-node crypto-operation log (written on every node)",
	"kmip_operations":                     "per-node KMIP operation log",
	"kmip_sessions":                       "KMIP connections held by this node",
	"ops_metrics_hourly":                  "per-node operation metrics",
	"pin_operations_log":                  "per-node PIN operation log",
	"platform_fips_observed":              "the FIPS mode this node runs",
	"policy_evaluations":                  "per-node policy decision log",
	"posture_engine_state":                "posture engine runtime state of this node",
	"posture_events_hot":                  "high-volume per-node event buffer",
	"reporting_error_telemetry":           "errors observed on this node",
	"secret_audit_log":                    "per-node secret access log",
	"signing_records":                     "signatures made on this node (written during crypto operations)",
	"threat_signals":                      "per-node threat signals raised from local traffic",
	"webhook_deliveries":                  "delivery attempts made by this node",
	"workload_identity_issuance":          "per-node issuance log",
}

// SharedAppend tables are append-only and written on every node; they are
// replicated in both directions (each node keeps its own chain) in a later
// slice. Until then they stay local to each node.
var SharedAppend = map[string]string{
	"audit_events":        "append-only; every node writes its own chain",
	"audit_merkle_epochs": "per-node Merkle epochs of the audit chain",
	"audit_merkle_leaves": "per-node Merkle leaves of the audit chain",
}
