#!/usr/bin/env python3
"""Docs name only routes that exist.

Every "METHOD /path" in docs/**/*.md must be a route some service registers
(services/ and pkg/, non-test Go). A /svc/<name>/ path is checked against the
service Envoy sends that prefix to, after Envoy strips it (infra/envoy). A
line that says the route was removed, or that there is none, is exempt, as
are Go code examples. Other exceptions go in scripts/doc-routes-allow.txt
with a reason.

  scripts/check-doc-routes.py              check (exit 1 on a mismatch)
  scripts/check-doc-routes.py --write-index  also rewrite the generated
                                             route index in API_REFERENCE.md

A route parameter matches a doc placeholder or an ID-like value, never a
plain lowercase word, so /certs/cas does not pass as /certs/{id}.
"""
import os
import re
import sys
from collections import defaultdict

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
os.chdir(ROOT)

METHODS = "GET|POST|PUT|PATCH|DELETE"
ROUTE_RE = re.compile(r'"(?:(%s) )?(/[^"\s]*)"' % METHODS)
REGISTER_RE = re.compile(r'(?:HandleFunc|Handle)\(\s*"(?:(%s) )?(/[^"\s]*)"' % METHODS)
DOC_RE = re.compile(r"\b(%s)\s+`?(/[A-Za-z0-9_\-/{}:.<>$]+)" % METHODS)
# A URL to an edge service path, e.g. in a curl example; "-X METHOD" before
# it names the method, otherwise any method will do.
URL_RE = re.compile(r"""(?:-X\s+(%s)\s+)?["']?https?://[^/\s"']+(/svc/[A-Za-z0-9_\-/{}:.<>$]+)""" % METHODS)
# A table row naming a method and an edge path in separate cells.
TABLE_RE = re.compile(r"\|\s*`?((?:%s)(?:/(?:%s))*)`?\s*\|\s*`(/svc/[A-Za-z0-9_\-/{}:.<>$]+)" % (METHODS, METHODS))
EXEMPT_RE = re.compile(r"\b(removed|no longer|there is no|does not exist)\b", re.I)
INDEX_START = "<!-- route-index:start (generated by scripts/check-doc-routes.py --write-index) -->"
INDEX_END = "<!-- route-index:end -->"


def collect_routes():
    routes = defaultdict(set)  # service dir -> {(method or "*", path)}
    for top in ("services", "pkg"):
        for dp, _, files in os.walk(top):
            for f in files:
                if not f.endswith(".go") or f.endswith("_test.go"):
                    continue
                src = open(os.path.join(dp, f), errors="ignore").read()
                svc = dp.split(os.sep)[1] if top == "services" else "_pkg"
                for m in ROUTE_RE.finditer(src):
                    if m.group(1):
                        routes[svc].add((m.group(1), m.group(2)))
                for m in REGISTER_RE.finditer(src):
                    routes[svc].add((m.group(1) or "*", m.group(2)))
    return routes


def envoy_prefixes(routes):
    env = open("infra/envoy/envoy.yaml").read()
    out = {}
    for m in re.finditer(r'prefix: "/svc/([a-z0-9-]+)/" \}\s*\n\s*route: \{ cluster: ([a-z0-9_]+)', env):
        name = m.group(2)[: -len("_http")].replace("_", "-") if m.group(2).endswith("_http") else m.group(2)
        for cand in (name, name + "-manager", name.replace("-", "")):
            if cand in routes:
                out[m.group(1)] = cand
                break
    return out


def segments(path):
    return [("*" if s.startswith(("{", ":", "<", "$")) else s) for s in path.split("?")[0].rstrip("/").split("/")]


def matches(pattern, path, literal_siblings=frozenset()):
    """literal_siblings: (index, prefix, suffix) positions where another route
    of the same method and shape has a literal segment, so a plain word there
    must be literal."""
    a, b = segments(pattern), segments(path)
    rest = a and a[-1] == "*" and pattern.rstrip("/").endswith("...}")
    if (len(b) < len(a)) if rest else (len(a) != len(b)):
        return False
    for k, (x, y) in enumerate(zip(a[:-1] if rest else a, b)):
        if x == y or y == "*":
            continue
        if x != "*":
            return False
        # A route parameter takes a placeholder or an ID-like value; a plain
        # word only when no sibling route has a literal there (/certs/cas is
        # not /certs/{id} next to /certs/ca).
        if re.fullmatch(r"[a-z][a-z-]*", y) and (k, tuple(b[:k]), tuple(b[k + 1:])) in literal_siblings:
            return False
    return True


def exists(routes, method, path, svc=None):
    pools = [routes[svc], routes["_pkg"]] if svc else list(routes.values())
    cands = [(m, p) for pool in pools for m, p in pool if method == "*" or m in (method, "*")]
    siblings = set()
    for _, p in cands:
        segs = segments(p)
        for k, seg in enumerate(segs):
            if seg != "*":
                siblings.add((k, tuple(segs[:k]), tuple(segs[k + 1:])))
    return any(matches(p, path, siblings) for _, p in cands)


def check(routes, prefixes, allow):
    bad = []
    for dp, _, files in os.walk("docs"):
        for f in sorted(files):
            if not f.endswith(".md"):
                continue
            path = os.path.join(dp, f)
            fence = None
            text = open(path, errors="ignore").read().split("\n")
            for n, line in enumerate(text, 1):
                if line.startswith("```"):
                    fence = None if fence is not None else line[3:].strip()
                    continue
                # A removal is often said in the sentence around the route.
                near = " ".join(text[max(0, n - 3):n + 2])
                if fence == "go" or EXEMPT_RE.search(near) or INDEX_START in line:
                    continue
                refs = [(m.group(1), m.group(2)) for m in DOC_RE.finditer(line)]
                refs += [(m.group(1) or "*", m.group(2)) for m in URL_RE.finditer(line)]
                refs += [(meth, m.group(2)) for m in TABLE_RE.finditer(line) for meth in m.group(1).split("/")]
                for meth, ref in refs:
                    ref = ref.rstrip(".,:;)")
                    if (meth, ref) in allow or "{service}" in ref or ref in ("/svc", "/svc/"):
                        continue
                    sm = re.match(r"^/svc/([a-z0-9-]+)(/.*)?$", ref)
                    if sm:
                        svc = prefixes.get(sm.group(1))
                        rest = sm.group(2) or "/"
                        if svc is not None and rest.endswith("/"):
                            # A base path: some route of the service lives under it.
                            ok = any(p.startswith(rest) for _, p in routes[svc])
                        else:
                            ok = svc is not None and exists(routes, meth, rest, svc)
                    else:
                        ok = exists(routes, meth, ref)
                    if not ok:
                        bad.append("%s:%d: %s %s" % (path, n, meth, ref))
    return bad


def write_index(routes, prefixes):
    by_svc = {v: k for k, v in prefixes.items()}
    lines = [INDEX_START, "", "Every route each service registers, as reached through the edge. Generated",
             "from the code; do not edit by hand.", ""]
    for svc in sorted(by_svc):
        lines.append("### %s (`/svc/%s/`)" % (svc, by_svc[svc]))
        lines.append("")
        for m, p in sorted(routes[svc], key=lambda r: (r[1], r[0])):
            lines.append("- `%s /svc/%s%s`" % ("ANY" if m == "*" else m, by_svc[svc], p))
        lines.append("")
    lines.append(INDEX_END)
    ref = "docs/API_REFERENCE.md"
    doc = open(ref).read()
    block = "\n".join(lines)
    if INDEX_START in doc:
        doc = re.sub(re.escape(INDEX_START) + ".*?" + re.escape(INDEX_END), lambda _: block, doc, flags=re.S)
    else:
        doc = doc.rstrip("\n") + "\n\n## Appendix: Route index (generated)\n\n" + block + "\n"
    open(ref, "w").write(doc)


def main():
    routes = collect_routes()
    prefixes = envoy_prefixes(routes)
    allow = set()
    if os.path.exists("scripts/doc-routes-allow.txt"):
        for line in open("scripts/doc-routes-allow.txt"):
            parts = line.split("#")[0].split()
            if len(parts) >= 2:
                allow.add((parts[0], parts[1]))
    if "--write-index" in sys.argv:
        write_index(routes, prefixes)
    bad = check(routes, prefixes, allow)
    if bad:
        print("FAIL [doc-routes]: docs name routes no service registers:")
        print("\n".join("  " + b for b in bad))
        return 1
    print("PASS [doc-routes]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
