CREATE TABLE IF NOT EXISTS governance_system_state (
    tenant_id              TEXT PRIMARY KEY,
    fips_mode              TEXT NOT NULL DEFAULT 'disabled',
    hsm_mode               TEXT NOT NULL DEFAULT 'software',
    cluster_mode           TEXT NOT NULL DEFAULT 'standalone',
    license_key            TEXT,
    license_status         TEXT NOT NULL DEFAULT 'inactive',
    mgmt_ip                TEXT,
    cluster_ip             TEXT,
    dns_servers            TEXT,
    ntp_servers            TEXT,
    tls_mode               TEXT NOT NULL DEFAULT 'internal_ca',
    tls_cert_pem           TEXT,
    tls_key_pem            TEXT,
    tls_ca_bundle_pem      TEXT,
    backup_schedule        TEXT NOT NULL DEFAULT 'daily@02:00',
    backup_target          TEXT NOT NULL DEFAULT 'local',
    backup_retention_days  INTEGER NOT NULL DEFAULT 30,
    backup_encrypted       BOOLEAN NOT NULL DEFAULT TRUE,
    proxy_endpoint         TEXT,
    snmp_target            TEXT,
    updated_by             TEXT,
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
