bind * -::*
protected-mode no
port 6379

dir /data
dbfilename dump.rdb

appendonly yes
appenddirname appendonlydir
appendfsync everysec

save 3600 1 300 100 60 10000

io-threads 2
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
